/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffb3af",
        "surface-bright": "#343b36",
        "surface-container-high": "rgb(var(--surface-high-rgb) / <alpha-value>)",
        "on-tertiary-container": "#711419",
        "secondary-fixed": "#71f8e4",
        "surface-container": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb) / <alpha-value>)",
        "inverse-primary": "#006c49",
        "outline": "rgb(var(--outline-rgb) / <alpha-value>)",
        "on-tertiary": "#650911",
        "on-secondary-container": "#003f38",
        "surface-container-low": "rgb(var(--surface-low-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "#ffb3af",
        "secondary-container": "#04b4a2",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "secondary": "rgb(var(--color-secondary-rgb) / <alpha-value>)",
        "on-error": "#690005",
        "surface-container-lowest": "rgb(var(--surface-lowest-rgb) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-rgb) / <alpha-value>)",
        "on-primary": "#003824",
        "surface-container-highest": "rgb(var(--surface-highest-rgb) / <alpha-value>)",
        "on-tertiary-fixed": "#410005",
        "on-surface": "rgb(var(--color-heading-rgb) / <alpha-value>)",
        "surface": "rgb(var(--color-bg-rgb) / <alpha-value>)",
        "inverse-on-surface": "#2b322d",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#005048",
        "on-tertiary-fixed-variant": "#842225",
        "on-secondary": "#003731",
        "surface-dim": "rgb(var(--color-bg-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "#4fdbc8",
        "primary": "rgb(var(--color-primary-rgb) / <alpha-value>)",
        "on-error-container": "#ffdad6",
        "surface-variant": "rgb(var(--surface-highest-rgb) / <alpha-value>)",
        "error-container": "#93000a",
        "on-primary-container": "var(--on-primary-container)",
        "inverse-surface": "rgb(var(--color-heading-rgb) / <alpha-value>)",
        "on-primary-fixed-variant": "#005236",
        "on-surface-variant": "rgb(var(--color-on-surface-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-surface-rgb) / <alpha-value>)",
        "background": "rgb(var(--color-bg-rgb) / <alpha-value>)",
        "tertiary-fixed": "#ffdad7",
        "tertiary-container": "#fc7c78",
        "on-secondary-fixed": "#00201c",
        "surface-tint": "rgb(var(--color-primary-rgb) / <alpha-value>)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "section-gap": "120px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Poppins"],
        "body-lg": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-sm": ["Poppins"],
        "headline-md": ["Poppins"],
        "display-xl": ["Poppins"],
        "display-lg-mobile": ["Poppins"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-mono": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-xl": ["100px", { "lineHeight": "0.9", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "display-lg-mobile": ["48px", { "lineHeight": "1.0", "fontWeight": "800" }]
      }
    },
  },
  plugins: [],
}
